MinhaEscola/Models/ContatoModel.cs
namespace MinhaEscola.Models
{
    public class ContatoModel
    {
        public int Id { get; set; }
        public string Email { get; set; } = "";
        public string Telefone { get; set; } = "";
        public string Nome { get; set; } = "";
        public string SobreNome { get; set; } = "";
        public string Cidade { get; set; } = "";
        public string Estado { get; set; } = "";
        public string Cep { get; set; } = "";
        public bool ReceberInf { get; set; }
        public bool Contatado { get; set; }

    }
}

MinhaEscola/Models/ErrorViewModel.cs
namespace MinhaEscola.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MinhaEscola/Models/LoginModel.cs
namespace MinhaEscola.Models
{
    public class LoginModel
    {
        public int Id { get; set; }
        public string Email { get; set; } = "";
        public string Senha { get; set; } = "";

    }
}

MinhaEscola/Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;
using MinhaEscola.Dominio.Entidades;
using MinhaEscola.Models;
using MinhaEscola.Repositorio;
using System.Diagnostics;

namespace MinhaEscola.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult IncluirContatoC(ContatoModel contato)
        {
            EContatos cont = new EContatos(
                contato.Id,
                contato.Email, 
                contato.Telefone,
                contato.Nome,
                contato.SobreNome, 
                contato.Cidade, 
                contato.Estado,
                contato.Cep, 
                contato.ReceberInf, 
                contato.Contatado
                );

            if(new ContatoRepositorio(cont).Gravar())
            {
                TempData["AlertMessage"] = "Recebemos seu pedido de contato. Em breve entraremos em contato.";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["AlertMessage"] = "Ocorreu algum erro ao receber seus dados. Tente novamente mais tarde.";
                return RedirectToAction("Index");
            }

        }
    }
}

MinhaEscola/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MinhaEscola.Models;
using System.Diagnostics;

namespace MinhaEscola.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MinhaEscola/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using MinhaEscola.Dominio.Entidades;

using MinhaEscola.Models;
using MinhaEscola.Repositorio;
using MinhaEscola.Repositorio.Interfaces;
using MinhaEscola.Views.Home;
using System.Runtime.CompilerServices;

namespace MinhaEscola.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Entrar(LoginModel login)
        {

            ELogin log = new ELogin(login.Id, login.Email, login.Senha);

            if (!new LoginRepositorio(log).ChekLongin())
            {
                TempData["AlertMessage"] = "Email ou Senha não cadastrado na base de dados.";
                return RedirectToAction("Index");
            }
            
            //Manda gravar os dados
            return RedirectToAction("Index");
        }
    }
}

MinhaEscola/Views/Contato/Index.cshtml
@model ContatoModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@


@{
    ViewData["Title"] = "Entre em Contato";
}
<h1 class="display-4">@ViewData["Title"]</h1>

 
@if (TempData["AlertMessage"] != null)
{
    <div class="alert alert-info">
        <strong>Contato</strong> @TempData["AlertMessage"]
    </div>
}
<div class="container">
    <p class="display-7">Entre em contato com a nossa equipe.</p>
    <div class="align-content-center">
        <div class="p-3 border bg-light shadow">
            <form class="row g-3 needs-validation" asp-controller="Contato" asp-action="IncluirContatoC" method="post">
                <div class="col-md-12">
                    <input type="email" asp-for="Email" class="form-control" id="Email" value="" required, placeholder="Email">
                    <div class="valid-feedback">
                        Looks good!
                    </div>
                </div>
                <div class="col-md-6">
                    <input type="tel" asp-for="Telefone" class="form-control" id="Telefone" value="" required, placeholder="Telefone">
                    <div class="valid-feedback">
                        Looks good!
                    </div>
                </div>
                <div class="col-md-6">
                    <input type="text" asp-for="Nome" class="form-control" id="validationCustom01" value="" required, placeholder="Nome">
                    <div class="valid-feedback">
                        Looks good!
                    </div>
                </div>
                <div class="col-md-6">
                    <input type="text" asp-for="SobreNome" class="form-control" id="validationCustom02" placeholder="Sobrenome" required>
                    <div class="valid-feedback">
                        Looks good!
                    </div>
                </div>
                <div class="col-md-6">
                    <input type="text" asp-for="Cidade" class="form-control" id="validationCustom03" placeholder="Cidade" required>
                    <div class="invalid-feedback">
                        Please provide a valid city.
                    </div>
                </div>
                <div class="col-md-6">
                    <select asp-for="Estado" class="form-select" id="validationCustom04" required>
                        <option selected disabled value="">Estado...</option>
                        <option>Acre</option>
                        <option>Alagoas</option>
                        <option>Amapá</option>
                        <option>Amazonas</option>
                        <option>Bahia</option>
                        <option>Ceará</option>
                        <option>Espírito Santo</option>
                        <option>Goiás</option>
                        <option>Maranhão</option>
                        <option>Mato Grosso</option>
                        <option>Mato Grosso do Sul</option>
                        <option>Minas Gerais</option>
                        <option>Pará</option>
                        <option>Paraíba</option>
                        <option>Paraná</option>
                        <option>Pernambuco</option>
                        <option>Piauí</option>
                        <option>Rio de Janeiro</option>
                        <option>Rio Grande do Norte</option>
                        <option>Rio Grande do Sul</option>
                        <option>Rondônia</option>
                        <option>Roraima</option>
                        <option>Santa Catarina</option>
                        <option>São Paulo</option>
                        <option>Sergipe</option>
                    </select>
                    <div class="invalid-feedback">
                        Please select a valid state.
                    </div>
                </div>
                <div class="col-md-3">
                    <input type="text" asp-for="Cep" class="form-control" id="validationCustom05" placeholder="CEP" required>
                    <div class="invalid-feedback">
                        Please provide a valid zip.
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-check">
                        <input asp-for="ReceberInf" class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                        <label class="form-check-label" for="invalidCheck">
                            Quero receber informações do Amigo da escola
                        </label>
                        <div class="invalid-feedback">
                            You must agree before submitting.
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <button class="btn btn-primary" type="submit">Enviar</button>
                </div>
            </form>
        </div>
    </div>
</div>

MinhaEscola/Views/Home/Contato.cshtml
@{
    ViewData["Title"] = "Entre em Contato";
}
<h1 class="display-4">@ViewData["Title"]</h1>

<p class="display-7">Entre em contato com a nossa equipe.</p>
<div class="container">
    <div class="col-6">
        <div class="p-3 border bg-light">
            <form class="row g-3 needs-validation" novalidate>
                <div class="col-md-12">
                    <input type="email" class="form-control" id="Email" value="" required, placeholder="Email">
                    <div class="valid-feedback">
                        Looks good!
                    </div>
                </div>
                <div class="col-md-6">
                    <input type="tel" class="form-control" id="Telefone" value="" required, placeholder="Telefone">
                    <div class="valid-feedback">
                        Looks good!
                    </div>
                </div>
                  <div class="col-md-6">
                    <input type="text" class="form-control" id="validationCustom01" value="" required, placeholder="Nome">
                    <div class="valid-feedback">
                      Looks good!
                    </div>
                  </div>
                  <div class="col-md-6">
                    <input type="text" class="form-control" id="validationCustom02" placeholder="Sobrenome" required>
                    <div class="valid-feedback">
                      Looks good!
                    </div>
                  </div>
                  <div class="col-md-6">
                    <input type="text" class="form-control" id="validationCustom03" placeholder="Cidade" required>
                    <div class="invalid-feedback">
                      Please provide a valid city.
                    </div>
                  </div>
                  <div class="col-md-6">
                    <select class="form-select" id="validationCustom04" required>
                      <option selected disabled value="">Estado...</option>
                            <option>Acre</option>
                            <option>Alagoas</option>
                            <option>Amapá</option>
                            <option>Amazonas</option>
                            <option>Bahia</option>
                            <option>Ceará</option>
                            <option>Espírito Santo</option>
                            <option>Goiás</option>
                            <option>Maranhão</option>
                            <option>Mato Grosso</option>
                            <option>Mato Grosso do Sul</option>
                            <option>Minas Gerais</option>
                            <option>Pará</option>
                            <option>Paraíba</option>
                            <option>Paraná</option>
                            <option>Pernambuco</option>
                            <option>Piauí</option>
                            <option>Rio de Janeiro</option>
                            <option>Rio Grande do Norte</option>
                            <option>Rio Grande do Sul</option>
                            <option>Rondônia</option>
                            <option>Roraima</option>
                            <option>Santa Catarina</option>
                            <option>São Paulo</option>
                            <option>Sergipe</option>
                    </select>
                    <div class="invalid-feedback">
                      Please select a valid state.
                    </div>
                  </div>
                  <div class="col-md-3">
                    <input type="text" class="form-control" id="validationCustom05" placeholder="CEP" required>
                    <div class="invalid-feedback">
                      Please provide a valid zip.
                    </div>
                  </div>
                  <div class="col-12">
                    <div class="form-check">
                      <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                      <label class="form-check-label" for="invalidCheck">
                        Quero receber informações do Amigo da escola
                      </label>
                      <div class="invalid-feedback">
                        You must agree before submitting.
                      </div>
                    </div>
                  </div>
                  <div class="col-12">
                    <button class="btn btn-primary" type="submit">Enviar</button>
                  </div>
            </form>
        </div>
    </div>
</div>

MinhaEscola/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Amigo da Escola";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo ao Amigo da Escola</h1>
    <p>Amigo da Escola é uma ferramenta para ajudar o acompanhamento de Alunos e Professores</p>
</div>

<div class="container">
    <div class="row g-2">
        <div class="col-6">
            <div class="p-3 border bg-light">
                <h1>Cadastre Lunos</h1>
                <p>Cadastre alunos para ter informaçõe sobre o aluno assim como:</p>
                <ul>
                    <li>Endereço</li>
                    <li>Telefone</li>
                    <li>Pais ou Responsáveis</li>
                    <li>Histórico</li>
                </ul>
            </div>
        </div>
        <div class="col-6">
            <div class="p-3 border bg-light">
                <h1>Registro de Notas Para Alunos</h1>
                <p>Registre as notas e tenha um acompanhamento como:</p>
                <ul>
                    <li>Calculo de média</li>
                    <li>Resultado altomatico</li>
                    <li>Monitora alunos com notas baixas</li>
                    <li>Verificação de matérias que precisão de mais atenção</li>
                </ul>
            </div>
        </div>
        <div class="col-6">
            <div class="p-3 border bg-light">
                <h1>Cadastro de Professores</h1>
                <p>Cadastre professores para ter informaçõe sobre o professor assim como:</p>
                <ul>
                    <li>Endereço</li>
                    <li>Telefone</li>
                    <li>Contatos</li>
                    <li>Histórico</li>
                </ul>
            </div>
        </div>
        <div class="col-6">
            <div class="p-3 border bg-light">
                <h1>Controle Financeiro</h1>
                <p>Registros financeiros como:</p>
                <ul>
                    <li>Contas a Pagar</li>
                    <li>Contas a Receber</li>
                    <li>Controle de Vencimentos</li>
                    <li>Calculo de Juros</li>
                </ul>
            </div>
        </div>
    </div>
</div>

MinhaEscola/Views/Login/Index.cshtml
@model LoginModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@if(TempData["AlertMessage"] != null)
{
    <div class="alert alert-info">
        <strong>E-mail</strong> @TempData["AlertMessage"]
    </div>
}

<div class="container">
    <label class="text-start">Entrar no Sistema</label>
    <div class="p-3 border bg-light shadow align-content-center">
        <div class="col-20">
            <form class="text-light" asp-controller="Login" asp-action="Entrar" method="post">
                <div class="mb-3">
                    <input type="email" required asp-for="Email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="E-mail">
                </div>
                <div class="mb-3">
                    <input type="password" required asp-for="Senha" class="form-control" id="exampleInputPassword1" placeholder="Senha">
                </div>
                
                <button type="submit" class="btn btn-primary">Entrar</button>
                
            </form>
        </div>
    </div>
</div>

MinhaEscola/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MinhaEscola</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MinhaEscola.styles.css" asp-append-version="true" />
 </head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index" >
                    <img src="~/Img/school.png" width="50" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Entre em Contato</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Entrar no Sistema</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privado</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Amigo da escola - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
            <label>Tecnolotias:</label>
            <img src="~/img/aspnet.png" width="200" height="100" />
            <img src="~/img/csharp.jpg" width="50" height="50" />
            <img src="~/img/sqlServer.png" width="100" height="50" />
            <img src="~/img/amazon.png" width="100" height="50" />
            <img src="~/img/bootstrap.png" width="50" height="50" />
        </div>
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>